apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knote-js-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fred4impact/knote-js-app-chart.git'
    targetRevision: HEAD
    path: knote-js-app-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true