version: "3.8"

services:
  app:
    build: .
    container_name: knote-js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - ./public/uploads:/app/public/uploads # Persist uploaded images

  mongo:
    image: mongo:5
    container_name: knote-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
